name: ci

on:
  push:
  pull_request:
  
env:
  GOPROXY: https://proxy.golang.org,direct
  GOSUMDB: sum.golang.org
  GONOPROXY: ""
  GONOSUMDB: ""
  GOPRIVATE: ""

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://proxy.golang.org,direct
      GOSUMDB: sum.golang.org
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true
          env:
          GOPROXY: https://proxy.golang.org,direct
          GOSUMDB: sum.golang.org

      - name: Prepare testdata modules FIRST
        run: |
          cd pkg/analyzer/testdata || exit 1
          go mod tidy
          cd ../..

      - name: Go fmt check
        run: test -z "$(gofmt -l .)"
  
      - name: Unit tests
        env:
          GOPROXY: https://proxy.golang.org,direct
          GOSUMDB: sum.golang.org
        run: |
          go test ./...

  build-custom-gcl:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
             | sh -s -- -b ./bin v2.10.1
          ./bin/golangci-lint --version

      - name: Build custom-gcl (with loglinter)
        run: |
          ./bin/golangci-lint custom -v -c .custom-gcl.yml
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-gcl-linux-amd64
          path: custom-gcl
