name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://proxy.golang.org,direct"
      GOSUMDB: "sum.golang.org"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true

      - name: Go fmt check
        run: |
          test -z "$(gofmt -l .)"
      - name: Go env (before)
        run: |
          go env GOPROXY GOSUMDB GOPRIVATE GONOPROXY GONOSUMDB
          env | sort | grep -E '^(GO(PROXY|SUMDB|PRIVATE|NO(PROXY|SUMDB))=)'

      - name: Force module proxy (workaround)
        run: |
          echo "GOPROXY=https://proxy.golang.org,direct" >> $GITHUB_ENV
          echo "GOSUMDB=sum.golang.org" >> $GITHUB_ENV

      - name: Go env (after)
        run: |
          go env GOPROXY GOSUMDB
          go env -w GOPROXY=https://proxy.golang.org,direct
          go env -w GOSUMDB=sum.golang.org
          go env GOPROXY GOSUMDB

      - name: Unit tests
        run: |
          go test ./...

  build-custom-gcl:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
             | sh -s -- -b ./bin v2.10.1
          ./bin/golangci-lint --version

      - name: Build custom-gcl (with loglinter)
        run: |
          ./bin/golangci-lint custom -v -c .custom-gcl.yml
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-gcl-linux-amd64
          path: custom-gcl
